; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "AGEIS XII"
#define MyAppVersion "2.0"
#define MyAppPublisher "ASD Solutions, Inc."
#define MyAppURL "https://aegisxii.vercel.app/"
#define MyAppExeName "firewall.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{B105FD15-8A21-4CC3-8AA9-C36CD5C8EC0C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}

; Architecture settings
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Installer privileges and styling
PrivilegesRequired=admin
DisableProgramGroupPage=yes
WizardStyle=modern
SolidCompression=yes

; Files and Outputs
LicenseFile=D:\AASHISH\Projects\Firewall\license.txt.txt
InfoBeforeFile=D:\AASHISH\Projects\Firewall\readme_before.txt.txt
InfoAfterFile=D:\AASHISH\Projects\Firewall\readme_after.txt.txt
OutputDir=C:\Users\hp\OneDrive\Desktop
OutputBaseFilename=AGEIS_XII_Setup_v2
SetupIconFile=C:\Users\hp\Downloads\Gemini_Generated_Image_f934ovf934ovf934.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main Executable
Source: "D:\AASHISH\Projects\Firewall\cmake-build-release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; Configuration and Dashboard Assets
Source: "D:\AASHISH\Projects\Firewall\config\*"; DestDir: "{app}\config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\AASHISH\Projects\Firewall\dashboard\*"; DestDir: "{app}\dashboard"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Dirs]
; Creates the logs directory inside the installation folder
Name: "{app}\logs"

[Run]
; Runs the firewall immediately after install with proper privileges
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser
