directories:
  output: packed
  buildResources: build
appId: com.asd.aegis-xii
productName: AEGIS XII
win:
  icon: assets/icon.ico
  requestedExecutionLevel: requireAdministrator
extraResources:
  - from: ../cmake-build-release/firewall.exe
    to: bin/firewall.exe
  - from: ../dashboard
    to: dashboard
  - from: ../config
    to: config
publish: 'null'
files: []
electronVersion: 31.7.7
